test "spawn cats by type" when running minecraft "1.15.2":
	delete all cats
	set {_l} to location of spawn of world "world"
	spawn 5 all black cats at {_l}
	assert size of all cats = 5 with "Size of all cats is not 5"
	assert size of all all black cats = 5 with "Size of all all black cats is not 5"
	spawn 2 siamese cats at {_l}
	assert size of all cats = 7 with "Size of all cats is not 7"
	assert size of all siamese cats = 2 with "Size of all siamese cats is not 2"
	delete all siamese cats
	assert size of all cats = 5 with "Size of all cats is not 5 after delete 2 siamese cats"
	delete all cats
	assert size of all cats = 0 with "Size of all cats is greater than 0 after all were deleted"

test "spawn wolves by variant" when running minecraft "1.21.0":
	delete all wolves
	set {_l} to location of spawn of world "world"
	spawn 5 ashen wolves at {_l}
	assert size of all wolves = 5 with "Size of all wolves is not 5"
	assert size of all ashen wolves = 5 with "Size of all ashen wolves is not 5"
	spawn 2 rusty wolves at {_l}
	assert size of all wolves = 7 with "Size of all wolves is not 7"
	assert size of all rusty wolves = 2 with "Size of all rusty wolves is not 2"
	delete all rusty wolves
	assert size of all wolves = 5 with "Size of all wolves is not 5 after delete 2 rusty wolves"
	delete all wolves
	assert size of all wolves = 0 with "Size of all wolves is greater than 0 after all were deleted"
